<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Academic\Feb26\Script001 - Create Table acdm_grades.sql" />
    <EmbeddedResource Include="Academic\Feb26\Script002 - Create Table acdm_subjects.sql" />
    <EmbeddedResource Include="Academic\Feb26\Script003 - Create Table acdm_topics.sql" />
    <EmbeddedResource Include="Academic\Feb26\Script004 - Create Table acdm_question.sql" />
    <EmbeddedResource Include="Academic\Feb26\Script005 - Create Table acdm_question_option.sql" />
    <EmbeddedResource Include="Academic\Feb26\Script006 - Add grade_uuid to acdm_subjects.sql" />
    <EmbeddedResource Include="Academic\Feb26\Script007 - Create Table acdm_question_grade.sql" />
    <EmbeddedResource Include="Academic\Feb26\Script008 - Alter correct_option to text.sql" />
    <EmbeddedResource Include="Academic\Feb26\Script009 - Create Table acdm_quiz.sql" />
    <EmbeddedResource Include="Academic\Feb26\Script010 - Add assessment_type to acdm_quiz.sql" />
    <EmbeddedResource Include="Academic\Feb26\Script011 - Create Table acdm_quiz_topic.sql" />
    <EmbeddedResource Include="Academic\Feb26\Script012 - Create Table acdm_school.sql" />
    <EmbeddedResource Include="Academic\Feb26\Script013 - Add school_uuid to acdm_quiz.sql" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="UserAccount\Feb26\Script001 - Create Table.sql" />
    <EmbeddedResource Include="UserAccount\Feb26\Script002 - Insert Data into Roles.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dbup-core" Version="6.0.15" />
    <PackageReference Include="dbup-postgresql" Version="6.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.3" />
    <PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.4" />
  </ItemGroup>

  <ItemGroup>
    <None Update="dbup.appsetting.development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="dbup.appsetting.local.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
